### ISSUE TITLE
[严重BUG]似乎是路径问题

### ISSUE THREAD

**Issue by CN-Yuncan** [BetterNCM/StyleSnippet#6]
第 1 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 11)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

第 2 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 11)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

第 3 次加载发生错误：
Error: 插件脚本 C:\betterncm/./plugins_runtime\StyleSnippet/index.js 加载出错: Error: directory_iterator::directory_iterator: 系统找不到指定的路径。: "C:\betterncm/./StyleSnippets"
    at F (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6664)
    at vr (eval at n (betterncm://betterncm/framework.js:1:22381), <anonymous>:30:6850)
    at Yo (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:57932)
    at va (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:104171)
    at sc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96719)
    at ac (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:96644)
    at Ja (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:93674)
    at Ya (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:90438)
    at Mc (orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:111886)
    at orpheus://orpheus/vendor/@cloudmusic-desktop/vendors-rudio@0.1.x/vendors-rudio.pc-new.production.js:37:113129
    at n (betterncm://betterncm/framework.js:1:22487)
    at async l (betterncm://betterncm/framework.js:1:22703)
    at async Promise.all (index 11)
    at async ie (betterncm://betterncm/framework.js:1:23527)
    at async Promise.all (index 0)
    at async betterncm://betterncm/framework.js:4:428

**Comment by MicroCBer** [comment]
fixed

**Comment by CN-Yuncan** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
